### ISSUE TITLE
json of grafana example dashboard

### ISSUE THREAD

**Issue by genofire** [thannaske/rspamd-influxdb#1]
Would be really nice ... it is possible to spent so much time in designing dashboards

**Comment by thannaske** [comment]
The dashboard that is visible in the screenshot does not longer exist in the way you can see it there. My personal Grafana dashboard that makes use of the `rspamd-influxdb` script is highly integrated into several other data sources like Telegraf's system metrics collector and the mailCow API (which I use for my personal e-mail server). 

Thereby I don't see any deeper sense in sharing my dashboard as you won't be able to use it properly without those dependencies. Sorry.
