### ISSUE TITLE
leaking password

### ISSUE THREAD

**Issue by genofire** [thannaske/rspamd-influxdb#2]
please give another option to parse password (e.g. read from file or so).

For everybody at same server is the password readable by run `ps -aux` in the correct moment.

**Comment by thannaske** [comment]
You may now provide the `--config $path` argument to specify a JSON configuration file. Please see `README.md` for further information. 

Please be aware that this comes with the breaking change that you now need to explicitly specify the `--url` and `--password` parameter if you want to run the script without configuration file.
