### ISSUE TITLE
Issue with URL parameter (Could not send GET request to given URL)

### ISSUE THREAD

**Issue by badsmoke** [thannaske/rspamd-influxdb#6]
Hi I would like to use the tool, I have a mailcow server running with rspamd but this error message occurs when running:

 python3 rspamd-influxdb.py --url "domain.com/rspamd/" --password "secret"
Could not send GET request to given URL. Check url parameter!

where is the problem?

**Comment by thannaske** [comment]
Please try to explicitly put a http or https in front of the domain name itself.

**Comment by badsmoke** [comment]
thanks "http" works
